version: "3.7"

services:
  reverse-proxy:
    image: traefik
    ports:
      - 80:80
      - 8001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --api
      - --providers.docker
